CREATE MATERIALIZED VIEW wide_table_100cols_mv TO wide_table_100cols AS
SELECT 
    JSONExtractInt(_raw, 'after', 'id') as id,
    parseDateTimeBestEffort(JSONExtractString(_raw, 'after', 'created_at')) as created_at,
    JSONExtractInt(_raw, 'after', 'smallint_col') as smallint_col,
    JSONExtractInt(_raw, 'after', 'integer_col') as integer_col,
    JSONExtractInt(_raw, 'after', 'bigint_col') as bigint_col,
    toDecimal128OrNull(JSONExtractString(_raw, 'after', 'numeric_col'), 20) as numeric_col,
    toDecimal64OrNull(JSONExtractString(_raw, 'after', 'decimal_col'), 4) as decimal_col,
    JSONExtractFloat(_raw, 'after', 'real_col') as real_col,
    JSONExtractFloat(_raw, 'after', 'double_col') as double_col,
    JSONExtractString(_raw, 'after', 'money_col') as money_col,
    JSONExtractString(_raw, 'after', 'char_col') as char_col,
    JSONExtractString(_raw, 'after', 'varchar_col') as varchar_col,
    JSONExtractString(_raw, 'after', 'text_col') as text_col,
    JSONExtractString(_raw, 'after', 'citext_col') as citext_col,
    JSONExtractString(_raw, 'after', 'bytea_col') as bytea_col,
    JSONExtractBool(_raw, 'after', 'bool_col') as bool_col,
    toDateOrNull(JSONExtractString(_raw, 'after', 'date_col')) as date_col,
    JSONExtractString(_raw, 'after', 'time_col') as time_col,
    JSONExtractString(_raw, 'after', 'timetz_col') as timetz_col,
    parseDateTimeBestEffortOrNull(JSONExtractString(_raw, 'after', 'timestamp_col')) as timestamp_col,
    parseDateTimeBestEffortOrNull(JSONExtractString(_raw, 'after', 'timestamptz_col')) as timestamptz_col,
    JSONExtractString(_raw, 'after', 'interval_col') as interval_col,
    toUUIDOrNull(JSONExtractString(_raw, 'after', 'uuid_col')) as uuid_col,
    JSONExtractString(_raw, 'after', 'json_col') as json_col,
    JSONExtractString(_raw, 'after', 'jsonb_col') as jsonb_col,
    JSONExtractString(_raw, 'after', 'xml_col') as xml_col,
    JSONExtractString(_raw, 'after', 'bit_col') as bit_col,
    JSONExtractString(_raw, 'after', 'varbit_col') as varbit_col,
    toIPv4OrNull(JSONExtractString(_raw, 'after', 'inet_col')) as inet_col,
    JSONExtractString(_raw, 'after', 'cidr_col') as cidr_col,
    JSONExtractString(_raw, 'after', 'macaddr_col') as macaddr_col,
    JSONExtractString(_raw, 'after', 'macaddr8_col') as macaddr8_col,
    JSONExtractString(_raw, 'after', 'point_col') as point_col,
    JSONExtractString(_raw, 'after', 'lseg_col') as lseg_col,
    JSONExtractString(_raw, 'after', 'box_col') as box_col,
    JSONExtractString(_raw, 'after', 'path_col') as path_col,
    JSONExtractString(_raw, 'after', 'polygon_col') as polygon_col,
    JSONExtractString(_raw, 'after', 'circle_col') as circle_col,
    JSONExtractString(_raw, 'after', 'tsvector_col') as tsvector_col,
    JSONExtractString(_raw, 'after', 'tsquery_col') as tsquery_col,
    [] as int_array_col,
    [] as text_array_col,
    [] as uuid_array_col,
    JSONExtractString(_raw, 'after', 'int4range_col') as int4range_col,
    JSONExtractString(_raw, 'after', 'int8range_col') as int8range_col,
    JSONExtractString(_raw, 'after', 'numrange_col') as numrange_col,
    JSONExtractString(_raw, 'after', 'tsrange_col') as tsrange_col,
    JSONExtractString(_raw, 'after', 'tstzrange_col') as tstzrange_col,
    JSONExtractString(_raw, 'after', 'daterange_col') as daterange_col,
    map() as hstore_col,
    JSONExtractString(_raw, 'after', 'enum_mood_col') as enum_mood_col,
    JSONExtractString(_raw, 'after', 'email_dom_col') as email_dom_col,
    JSONExtractString(_raw, 'after', 'name_col') as name_col,
    JSONExtractUInt(_raw, 'after', 'oid_col') as oid_col,
    JSONExtractString(_raw, 'after', 'pg_lsn_col') as pg_lsn_col,
    JSONExtractString(_raw, 'after', 'txid_snapshot_col') as txid_snapshot_col,
    JSONExtractString(_raw, 'after', 'jsonpath_col') as jsonpath_col,
    JSONExtractString(_raw, 'after', 'int4multirange_col') as int4multirange_col,
    JSONExtractString(_raw, 'after', 'nummultirange_col') as nummultirange_col,
    JSONExtractString(_raw, 'after', 'tsmultirange_col') as tsmultirange_col,
    JSONExtractString(_raw, 'after', 'tstzmultirange_col') as tstzmultirange_col,
    JSONExtractString(_raw, 'after', 'datemultirange_col') as datemultirange_col,
    JSONExtractInt(_raw, 'after', 'smallint_col2') as smallint_col2,
    JSONExtractInt(_raw, 'after', 'integer_col2') as integer_col2,
    JSONExtractInt(_raw, 'after', 'bigint_col2') as bigint_col2,
    toDecimal64OrNull(JSONExtractString(_raw, 'after', 'numeric_col2'), 2) as numeric_col2,
    JSONExtractFloat(_raw, 'after', 'real_col2') as real_col2,
    JSONExtractFloat(_raw, 'after', 'double_col2') as double_col2,
    JSONExtractString(_raw, 'after', 'varchar_col2') as varchar_col2,
    JSONExtractString(_raw, 'after', 'text_col2') as text_col2,
    JSONExtractString(_raw, 'after', 'citext_col2') as citext_col2,
    JSONExtractString(_raw, 'after', 'char_col2') as char_col2,
    JSONExtractBool(_raw, 'after', 'bool_col2') as bool_col2,
    toDateOrNull(JSONExtractString(_raw, 'after', 'date_col2')) as date_col2,
    parseDateTimeBestEffortOrNull(JSONExtractString(_raw, 'after', 'timestamp_col2')) as timestamp_col2,
    parseDateTimeBestEffortOrNull(JSONExtractString(_raw, 'after', 'timestamptz_col2')) as timestamptz_col2,
    JSONExtractString(_raw, 'after', 'interval_col2') as interval_col2,
    toIPv4OrNull(JSONExtractString(_raw, 'after', 'inet_col2')) as inet_col2,
    JSONExtractString(_raw, 'after', 'macaddr_col2') as macaddr_col2,
    JSONExtractString(_raw, 'after', 'point_col2') as point_col2,
    JSONExtractString(_raw, 'after', 'polygon_col2') as polygon_col2,
    [] as int_array_col2,
    [] as text_array_col2,
    JSONExtractString(_raw, 'after', 'int4range_col2') as int4range_col2,
    JSONExtractString(_raw, 'after', 'daterange_col2') as daterange_col2,
    JSONExtractString(_raw, 'after', 'jsonb_col2') as jsonb_col2,
    JSONExtractString(_raw, 'after', 'json_col2') as json_col2,
    JSONExtractString(_raw, 'after', 'bytea_col2') as bytea_col2,
    JSONExtractString(_raw, 'after', 'bit_col2') as bit_col2,
    JSONExtractString(_raw, 'after', 'varbit_col2') as varbit_col2,
    JSONExtractString(_raw, 'after', 'tsvector_col2') as tsvector_col2,
    JSONExtractString(_raw, 'after', 'tsquery_col2') as tsquery_col2,
    JSONExtractString(_raw, 'after', 'xml_col2') as xml_col2,
    JSONExtractString(_raw, 'after', 'enum_mood_col2') as enum_mood_col2,
    JSONExtractString(_raw, 'after', 'email_dom_col2') as email_dom_col2,
    [] as bigint_array_col,
    JSONExtractString(_raw, 'after', 'numrange_col2') as numrange_col2,
    JSONExtractString(_raw, 'after', 'jsonpath_col2') as jsonpath_col2,
    JSONExtractString(_raw, 'after', 'pg_lsn_col2') as pg_lsn_col2,
    map() as hstore_col2,
    toUUIDOrNull(JSONExtractString(_raw, 'after', 'uuid_col2')) as uuid_col2,
    JSONExtractString(_raw, 'after', 'name_col2') as name_col2
FROM wide_table_100cols_kafka
